### ISSUE TITLE
[bug]页面问题

### ISSUE THREAD

**Issue by CodFrm** [scriptscat/scriptlist-frontend#11]
- [x] https://scriptcat.org/search 这个页面时，下面的页面只有首尾页
![image](https://user-images.githubusercontent.com/22783163/140301582-70afa8e6-f988-4fa7-90ec-393a90bca4ea.png)

- [x] bug 没填分数，什么反应都没有
- [x] 提交时应该转转圈圈和禁用
![2JF8)VZ0}SQBRATWQ08OYQM](https://user-images.githubusercontent.com/22783163/140301656-681c7fbd-182a-40fe-9f70-9deac25ee5ca.png)

**Comment by CodFrm** [comment]
- [ ] 这里标题应该不能再点击了
![image](https://user-images.githubusercontent.com/22783163/140301963-f19af770-80fa-43ef-aeca-d579784f57a5.png)

- [ ] 用户页完成后，点用户名应该跳转用户页
- [ ] 如何安装脚本应该新窗口打开

**Comment by Dandanla** [comment]
已全部修复
