### ISSUE TITLE
一些后面将支持的功能和现在的bug记录

### ISSUE THREAD

**Issue by CodFrm** [scriptscat/scriptlist-frontend#18]
- [x] 支持脚本设置归档状态（不再维护）
- [x] 用户脚本页筛选bug和用户脚本页页码
- [x] 底部图标未显示
- [x] 管理员对脚本的删除管理查看统计等操作
- [x] 提交反馈时登录判断（可能还有其他页面）
- [ ] 评分排序问题（现在貌似是按照数量来进行排序的）
- [ ] 允许加密的代码（审核机制）
- [ ] 加强捐助引导
- [ ]

**Comment by Hangover1230** [comment]
- [ ] 开发者发布与更新脚本时可额外增加脚本关键词，并展示在脚本标题下方（更方便用户搜索）
效果图：
![QQ图片20220122162712](https://user-images.githubusercontent.com/90684083/150631001-b7e34413-b82b-4bf3-a2f6-0fa17dffd080.png)
