### ISSUE TITLE
脚本列表反馈功能

### ISSUE THREAD

**Issue by CodFrm** [scriptscat/scriptlist-frontend#7]

**Comment by Hangover1230** [comment]
建议添加脚本排序选项，按安装量 评分 更新日期
ggnb！！！👍

**Comment by CodFrm** [comment]
> 建议添加脚本排序选项，按安装量 评分 更新日期 ggnb！！！👍

应该新开issue来着

![image](https://user-images.githubusercontent.com/22783163/140527790-ec17192c-1ed1-4082-812c-5e67af1dcd6c.png)

我是想着在这里增加一个查看更多的选项来实现 @Dandanla

**Comment by Hangover1230** [comment]
> > 建议添加脚本排序选项，按安装量 评分 更新日期 ggnb！！！👍
> 
> 应该新开issue来着
> 
> ![image](https://user-images.githubusercontent.com/22783163/140527790-ec17192c-1ed1-4082-812c-5e67af1dcd6c.png)
> 
> 我是想着在这里增加一个查看更多的选项来实现 @Dandanla

这不是就要跳转网页了吗 感觉在当前网页实时排序会好些

**Comment by Dandanla** [comment]
赞同 @CodFrm 的方法，因为分页处理无法直接进行排序的

**Comment by CodFrm** [comment]
@Dandanla 这里错误以后也一直转圈圈

![image](https://user-images.githubusercontent.com/22783163/141686812-8fee0578-4a80-43f0-b3c3-3649290fc1c6.png)

**Comment by Dandanla** [comment]
估计又是李恒道没catch到error
